$outputFile = "C:\Users\moyas\.gemini\antigravity\scratch\bbt-charasheet-app\js\arts_data.js"
$csvFolder = "C:\Users\moyas\.gemini\antigravity\scratch\bbt-charasheet-app\data\uploads"
$csvFiles = Get-ChildItem "$csvFolder\*.csv"
$result = [ordered]@{}

foreach ($file in $csvFiles) {
    if ($file.Name -match "装備\.csv$" -or $file.Name -match "道具\.csv$") {
        continue
    }

    if ($file.Name -match "^BBT_アーツデータ - (.+)\.csv$") {
        $category = $matches[1]
    } else {
        $category = $file.BaseName
    }
    
    $artsArray = @()
    
    # Read the full lines instead of using Import-Csv directly
    # because Import-Csv fails parsing on some weirdly formatted strings in different PS versions.
    $lines = Get-Content -Path $file.FullName -Encoding UTF8
    
    for ($i = 1; $i -lt $lines.Count; $i++) {
        $line = $lines[$i]
        if ([string]::IsNullOrWhiteSpace($line)) { continue }
        
        # Simple CSV split with regex matching comma outside quotes
        $parts = [regex]::Split($line, '(?<=^([^"]|"[^"]*")*),(?=(?:[^"]|"[^"]*")*$)')
        $row = @()
        foreach ($p in $parts) {
            if ($p -ne ",") {
                $stripped = $p -replace '^"|"$',''
                $row += $stripped.Trim()
            }
        }
        
        if ($row.Count -lt 11) { continue }
        
        $rootName = $row[1]
        $artName = $row[2]
        
        if ($rootName -eq "ルーツ" -and $artName -eq "アーツ名") { continue }
        if ([string]::IsNullOrWhiteSpace($rootName) -or [string]::IsNullOrWhiteSpace($artName)) { continue }
        
        $artObj = [ordered]@{
            "ルーツ"     = $rootName;
            "アーツ名"   = $artName;
            "種別"       = $row[3];
            "最大Lv"     = $row[4];
            "タイミング" = $row[5];
            "判定値"     = $row[6];
            "対象"       = $row[7];
            "射程"       = $row[8];
            "コスト"     = $row[9];
            "効果"       = $row[10]
        }
        $artsArray += $artObj
    }
    
    $result[$category] = $artsArray
}

# The trick below forces PS to not escape unicode characters.
# Depth 5 allows deeply nested objects.
$json = $result | ConvertTo-Json -Depth 5 -Compress
$warningComment = "/* =========================================================================`n * WARNING: DO NOT EDIT THIS FILE DIRECTLY!`n * This file is automatically generated from CSV files in the data/uploads folder.`n * Manual edits (such as missing commas) will cause syntax errors and break the app.`n * To update data, edit the CSV and run Update-ArtsData.ps1.`n * ========================================================================= */`n"
$jsContent = $warningComment + "const BBTArtsData = " + $json + ";"
[System.IO.File]::WriteAllText($outputFile, $jsContent, [System.Text.Encoding]::UTF8)

Write-Host "Created arts_data.js with categories."
