import os
import csv
import json
import codecs

csv_folder = os.path.join(os.path.dirname(__file__), 'data', 'uploads')
output_file = os.path.join(os.path.dirname(__file__), 'js', 'arts_data.js')

result = {}
files = os.listdir(csv_folder)

for f in files:
    if f.endswith('装備.csv') or f.endswith('道具.csv'):
        continue
    if not f.endswith('.csv'):
        continue

    category = f.replace('.csv', '')
    if f.startswith('BBT_アーツデータ - '):
        category = f.replace('BBT_アーツデータ - ', '').replace('.csv', '')
    
    arts_array = []
    with codecs.open(os.path.join(csv_folder, f), 'r', 'utf-8-sig') as csvfile:
        reader = csv.reader(csvfile)
        # Skip header
        try:
            next(reader)
        except:
            pass
        
        for row in reader:
            if len(row) < 11:
                continue
            root_name = row[1]
            art_name = row[2]
            
            if root_name == 'ルーツ' and art_name == 'アーツ名':
                continue
            if not root_name.strip() or not art_name.strip():
                continue
                
            arts_array.append({
                'ルーツ': root_name,
                'アーツ名': art_name,
                '種別': row[3],
                '最大Lv': row[4],
                'タイミング': row[5],
                '判定値': row[6],
                '対象': row[7],
                '射程': row[8],
                'コスト': row[9],
                '効果': row[10]
            })
            
    result[category] = arts_array

js_content = """/* =========================================================================
 * WARNING: DO NOT EDIT THIS FILE DIRECTLY!
 * This file is automatically generated from CSV files in the data/uploads folder.
 * Manual edits (such as missing commas) will cause syntax errors and break the app.
 * To update data, edit the CSV and run Update-ArtsData.ps1.
 * ========================================================================= */
""" + 'const BBTArtsData = ' + json.dumps(result, ensure_ascii=False, indent=2) + ';'

with codecs.open(output_file, 'w', 'utf-8') as f:
    f.write(js_content)
    
print('Generated arts_data.js successfully')
