$outputFile = "C:\Users\moyas\.gemini\antigravity\scratch\bbt-charasheet-app\js\equipment_data.js"
$equipCsv = "C:\Users\moyas\.gemini\antigravity\scratch\bbt-charasheet-app\data\uploads\BBT_アーツデータ - 装備.csv"
$itemCsv = "C:\Users\moyas\.gemini\antigravity\scratch\bbt-charasheet-app\data\uploads\BBT_アーツデータ - 道具.csv"

$result = [ordered]@{
    "weapons" = @()
    "armor" = @()
    "items" = @()
}

# Parse Equipment
if (Test-Path $equipCsv) {
    # Custom parsing due to potential empty columns
    $csvData = Import-Csv $equipCsv -Encoding UTF8 -Header "Exp","ルーツ","装備名","種別","命中","攻撃力","G値","ドッジ","A値","行動値","射程","購入","効果","Extra"
    foreach ($row in $csvData) {
        $name = $row."装備名"
        $type = $row."種別"
        if ([string]::IsNullOrWhiteSpace($name) -or $name -eq "装備名") { continue }
        
        $obj = [ordered]@{
            "ルーツ" = $row."ルーツ";
            "装備名" = $name;
            "種別" = $type;
            "命中" = $row."命中";
            "攻撃力" = $row."攻撃力";
            "G値" = $row."G値";
            "ドッジ" = $row."ドッジ";
            "A値" = $row."A値";
            "行動値" = $row."行動値";
            "射程" = $row."射程";
            "購入" = $row."購入";
            "効果" = $row."効果"
        }
        
        if ($type -match "武器" -or $type -match "乗り物") {
            $result["weapons"] += $obj
        } elseif ($type -match "防具") {
            $result["armor"] += $obj
        }
    }
}

# Parse Items
if (Test-Path $itemCsv) {
    $itemData = Import-Csv $itemCsv -Encoding UTF8 -Header "Exp","ルーツ","装備名","種別","タイミング","対象","射程","購入","効果","Extra1","Extra2"
    foreach ($row in $itemData) {
        $name = $row."装備名"
        if ([string]::IsNullOrWhiteSpace($name) -or $name -eq "装備名") { continue }
        
        $obj = [ordered]@{
            "ルーツ" = $row."ルーツ";
            "装備名" = $name;
            "種別" = $row."種別";
            "タイミング" = $row."タイミング";
            "対象" = $row."対象";
            "射程" = $row."射程";
            "購入" = $row."購入";
            "効果" = $row."効果"
        }
        $result["items"] += $obj
    }
}

$json = $result | ConvertTo-Json -Depth 5
$warningComment = "/* =========================================================================`n * WARNING: DO NOT EDIT THIS FILE DIRECTLY!`n * This file is automatically generated from CSV files in the data/uploads folder.`n * Manual edits (such as missing commas) will cause syntax errors and break the app.`n * To update data, edit the CSV and run Update-EquipmentData.ps1.`n * ========================================================================= */`n"
$jsContent = $warningComment + "const BBTEquipData = " + $json + ";"
[System.IO.File]::WriteAllText($outputFile, $jsContent, [System.Text.Encoding]::UTF8)

Write-Host "Created $outputFile with weapons, armor, and items."
